// <auto-generated />
using IndiaWalks.APi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndiaWalks.APi.Migrations
{
    [DbContext(typeof(IndiaWalksDbContext))]
    [Migration("20260318134747_WalksDataSeeded")]
    partial class WalksDataSeeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndiaWalks.APi.Domain.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Easy"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Hard"
                        });
                });

            modelBuilder.Entity("IndiaWalks.APi.Domain.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 162968.0,
                            Code = "AP",
                            Lat = 15.9129,
                            Long = 79.739999999999995,
                            Name = "Andhra Pradesh",
                            Population = 49577103L
                        });
                });

            modelBuilder.Entity("IndiaWalks.APi.Domain.Walks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DifficultyId")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DifficultyId = 1,
                            Length = 2.5,
                            Name = "Charminar Walk",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            DifficultyId = 1,
                            Length = 3.6000000000000001,
                            Name = "Marine drive stroll",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 3,
                            DifficultyId = 1,
                            Length = 1.5,
                            Name = "Golden Temple Circuit",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 4,
                            DifficultyId = 2,
                            Length = 4.2000000000000002,
                            Name = "Lalbagh Garden Walk",
                            RegionId = 5
                        });
                });

            modelBuilder.Entity("IndiaWalks.APi.Domain.Walks", b =>
                {
                    b.HasOne("IndiaWalks.APi.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IndiaWalks.APi.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
